<?php

$title = 'Zarządzaj kategorią: Ogłoszenia';
$this->headTitle($title);
$controllerName = 'sales-unit';

?>

<h1>
    <?= $this->escapeHtml($title);
    ?>
</h1>
<p>
    <a href="<?= $this->url('notice', ['controller' => 'notice', 'action' => 'sendAllNoticesToDomiporta']) ?>"
       class="btn btn-info">
        Wyślij ogłoszenia do Domiporta</a>

    <a href="<?= $this->url('notice', ['controller' => 'notice', 'action' => 'sendAllNoticesToOtodom']) ?>"
       class="btn btn-info">
        Wyślij ogłoszenia do Otodom</a>

    <a href="<?= $this->url('notice', ['controller' => 'notice', 'action' => 'sendAllNoticesToGumtree']) ?>"
       class="btn btn-info">
        Wyślij ogłoszenia do Gumtree</a>

    <a href="<?= $this->url('notice', ['action' => 'index']) ?>" class="btn btn-info">Powrót na stronę główną</a>
</p>
<table class="table">
    <tr>
        <th>Nazwa</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($returnData as $row) : ?>
        <tr>
            <td><?= $this->escapeHtml($row->title); ?></td>

            <td>
                <a href="<?= $this->url('notice', ['controller' => 'notice', 'action' => 'edit',
                    'id' => $row->id]) ?>">Edytuj</a>
            </td>
            <td>
                <a href="<?= $this->url('notice', ['controller' => 'notice', 'action' => 'delete',
                    'id' => $row->id]) ?>">Usuń</a>
            </td>
        </tr>

    <?php endforeach; ?>
