<?php

$title = 'Usuń Lokalizaję wg Otodom';
$this->headTitle($title);

$controllerName = 'location-otodom';

?><h1><?php $this->escapeHtml($title) ?> </h1>
<p>
    Czy chcesz usunąć wpis:
</p>
<h3>
    <?php echo $this->escapeHtml($dataToDelete->name) ?>
</h3>
<?php
$url = $this->url('notice', [
    'controller' => $controllerName,
    'action' => 'delete',
    'id' => $dataToDelete->id
]);
?>
<form method="post" action="<?= $url; ?>">
    <div>
        <input type="submit" name="del" value="Yes">
        <input type="submit" name="del" value="No">
    </div>
</form>